version: '3'

services:
  postgres:
    image: postgres:13.4-alpine3.14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=aaas
      - POSTGRES_PASSWORD=aaas
      - POSTGRES_DB=aaas
